### ISSUE TITLE
Unbalanced auto-wiki dataset

### ISSUE THREAD

**Issue by ghost** [chaojiang06/wiki-auto#1]
Hi there,

I believe that the number of phrases (rows) in train.dst is different from the number of phrases in the train.src file. 

Is this a mistake or am I missing something?

Thanks :)

**Comment by chaojiang06** [comment]
Hi, thanks for reaching out!

I double-checked them, both of them have 488,332 rows. Did you open them in the browser or clone the repo to the local disk?

**Comment by ghost** [comment]
Many thanks for the quick reply. I was getting rows of 487,935 and 488,101 for the two files while viewing them from excel (just so I could take a look at the data easily). 

But now I'm getting 488,332 rows on both files when simply counting the number of rows using a python script. I'm not sure why excel is having issues with it. 

Anyway, we are all good now, thanks again :)
